version: '3.7'

services:
  nginx:
    platform: linux/amd64
    build         :
      context: ./nginx
    image         : ichiichiban-web
    hostname      : ichiichiban-web
    container_name: ichiichiban-web
    depends_on    :
      - php
    ports         :
      - 80:80
    volumes       :
      - ./src:/var/www/ichiichiban:cached
  php:
    platform: linux/amd64
    build         :
      context: ./phpfpm
    image         : ichiichiban-php
    hostname      : ichiichiban-php
    container_name: ichiichiban-php
    volumes       :
      - ./src:/var/www/ichiichiban:cached
  mysql:
    platform: linux/amd64
    #restart: always
    build         :
      context: ./mysql
    image         : ichiichiban-db
    hostname      : ichiichiban-db
    container_name: ichiichiban-db
    volumes       :
      - ./mysql/data:/var/lib/mysql
    environment   :
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ichiichiban
    ports         :
      - 3306:3306
networks:
  default:
    name: ichiichiban-network